### ISSUE TITLE
utf-8 encoding should be default for the open() statement

### ISSUE THREAD

**Issue by silver-volt4** [guneetsinghchatha/subredditdownloader#1]
I found this script with google, it's insane that it's only been published yesterday.
Anyway, to make it work for me, I had to add this to the open() statement:
`encoding="utf-8"`
So that would make:
`with open(subreddit + '_' + thing + '_' + str(int(time.time())) + '.txt', 'w', encoding="utf-8") as f:`

other than that, thanks for the script, it's great!

**Comment by guneetsinghchatha** [comment]
Thank you so much for this - I will patch the issue ASAP
Also if you have issues with the data being in single quotes this seemed to fix all the data issues for me - https://gist.github.com/mbrzusto/23fe728966247f25f3ec

**Comment by silver-volt4** [comment]
You will most likely want to use f.write(json.dumps(data)) as a fix, instead of a plain str()
