### ISSUE TITLE
do this to fix the single quote thing

### ISSUE THREAD

**Issue by silver-volt4** [guneetsinghchatha/subredditdownloader#2]
Line 74
`f.write(str(post) + '\n')`
becomes
`f.write(json.dumps(post) + '\n')`

Make sure the json module is imported, it comes with python by default

**Comment by guneetsinghchatha** [comment]
Added both , thank you so much :)

**Comment by guneetsinghchatha** [comment]
It doesn't seem to solve the issue - could you please share your code so I can see the entire changes you made - I guess I have to change the variable name from JSON too

**Comment by silver-volt4** [comment]
You already have a `json` _variable_ defined above the line, which is a bad idea as it conflicts with the `json` _module_.
Import the `json` _module_ under a different name, perhaps by using `import json as JSON` and using `JSON.dumps()`
